// This file is auto-generated by specta. Do not edit.
// This file has been generated by Specta. Do not edit this file manually.
export type ChatDirection = "incoming" | "outgoing";

export type ChatEntry = {
	timestamp: string,
	direction: ChatDirection,
	chat_id: number,
	text: string,
};

export type ErrorRecord = {
	message: string,
	at: string,
};

// What a scheduled job does when it fires.
export type JobAction = 
// Run a prompt through Claude, send the result to a Telegram chat.
{ type: "claude_prompt"; prompt: string; chat_id: number } | 
// Send a static message to a Telegram chat.
{ type: "telegram_message"; chat_id: number; text: string } | 
// Send a static message to the admin.
{ type: "telegram_admin"; text: string };

// A scheduled job record.
export type JobRecord = {
	// User-facing stable ID (persisted across restarts).
	stable_id: string,
	name: string,
	cron_expression: string,
	action: JobAction,
	one_shot?: boolean,
};

// Runtime status snapshot, written periodically to status.json.
export type RuntimeStatus = {
	daemon_started_at: string,
	total_invocations: number,
	queue_depth: number,
	queue_full_rejections?: number,
	last_error: ErrorRecord | null,
	heartbeat_last_alert?: ErrorRecord | null,
	heartbeat_last_ok: string | null,
	heartbeat_enabled: boolean,
	scheduler_job_count: number,
	session_id_short: string | null,
};

export type SoulFile = {
	name: string,
	content: string,
};

export type SoulResponse = {
	files: SoulFile[],
};
